### ISSUE TITLE
centos 6中不起效果

### ISSUE THREAD

**Issue by 1265578519** [opsengine/cpulimit#100]
![image](https://user-images.githubusercontent.com/6442439/114938351-9a2c0000-9e71-11eb-9361-2470adb2f257.png)

**Comment by 1265578519** [comment]
他在centos 7中可以完全正常的工作。怎么修复这个问题？

**Comment by HiGarfield** [comment]
Try this:
https://github.com/HiGarfield/cpulimit
Tested in centos 6.

![](https://github.com/user-attachments/assets/c6b17106-d286-44ae-b0e4-9f62be4e9f4d)

**Comment by 1265578519** [comment]
> Try this: https://github.com/HiGarfield/cpulimit Tested in centos 6.
> 
> ![](https://private-user-images.githubusercontent.com/32226909/381255664-c6b17106-d286-44ae-b0e4-9f62be4e9f4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNDM4NDAsIm5iZiI6MTczMDI0MzU0MCwicGF0aCI6Ii8zMjIyNjkwOS8zODEyNTU2NjQtYzZiMTcxMDYtZDI4Ni00NGFlLWIwZTQtOWY2MmJlNGU5ZjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDIzMTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZDJiMTAzNjM5ZjY4YTdlNGI1MTA3ZWRkMWZjYmQyZjhmYTlkYTBlZDBhOGUzZGEyZWNjN2U5N2YzYjM5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NseUshxPdItE6h7sLt1pTyYTgtruQWpaZeCRPgeHP6w)


谢谢，我找到了进程发生高CPU的原因，是handle_accept函数引发死循环，软件供应方已经修改源代码修复，现在不需要使用cpulimit抑制CPU使用率
对于centos6的[cpulimit](https://github.com/HiGarfield/cpulimit)，稍后我也会测试可用性
