### ISSUE TITLE
Project location confusion

### ISSUE THREAD

**Issue by sshedi** [opsengine/cpulimit#112]
Hi @opsengine , I see cpulimit project hosted in sourceforge as well.

https://sourceforge.net/projects/limitcpu/

is this project same as the one hosted in github? Or sourceforge project is the updated version of this project? Can you please help out?.

**Comment by sshedi** [comment]
Hi @bkwzwz can you please check if it's okay if we consume the project from sourceforge instead of here?

**Comment by bkwzwz** [comment]
Yes. Looks like limitcpu has a newer version.  I check redhat build spec and it is pointing to there as well. c.c @sshedi

**Comment by sshedi** [comment]
Can you point me to the RHEL spec?

Fedora uses source from this github location.
https://src.fedoraproject.org/rpms/cpulimit/blob/rawhide/f/cpulimit.spec

**Comment by bkwzwz** [comment]
I found it from here:
https://bugzilla.redhat.com/show_bug.cgi?id=772406

**Comment by sshedi** [comment]
I see, I checked the history of fedora's cpulimit spec, they initially used source from sourceforge, then switched to github source.

I think it's okay to use the updated source from sourceforge again, thanks @bkwzwz. Closing this issue.
