### ISSUE TITLE
Process found but you aren't allowed to control it

### ISSUE THREAD

**Issue by lockheed** [opsengine/cpulimit#25]
I'm trying to limit CPU usage by cc1 and gcc compiles, but this is what I get. No matter if I run it with sudo or su.

$ cpulimit -l 10 -v -p 2083
2 cpu detected
Process found but you aren't allowed to control it

**Comment by fbrier** [comment]
I just ran into this issue when attempting to control how much CPU a make process could use. The -p pid approach always resulted in this error, but specifying the command as a cpulimit parameter worked great.
```
cpulimit -l 200 -i "/usr/bin/make"
```
