### ISSUE TITLE
What is 400% CPU?

### ISSUE THREAD

**Issue by kodekrendel** [opsengine/cpulimit#70]
It says `percentage of cpu allowed from 0 to 400 (required)`
Why 400?

**Comment by kn00tcn** [comment]
i assume that means you have a quadcore/thread cpu

100% would be one core, or what you expected as 25%

it's mildly useful when you want to know if a single threaded app is being maxed out rather than remembering which percentage adds up to one core

**Comment by kodekrendel** [comment]
Thanks, that make sense.

**Comment by kn00tcn** [comment]
i should mention i'm assuming that's the reason, i've never heard of cpulimit until today (& it seems abandoned), but do remember various linux tools counting above 1.0 or 100%
